services:
  - type: web
    name: expense-tracker-gql
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /
    autoDeploy: true
# Note: For MONGODB_URI, you need to manually add it in the Render dashboard:
# 1. Go to your service in the Render dashboard
# 2. Click on "Environment"
# 3. Add MONGODB_URI with your MongoDB connection string
# 4. Click "Save Changes"
